### ISSUE TITLE
Make Add-on Preferences clearer (add more explanations for buttons)

### ISSUE THREAD

**Issue by xan2622** [InamuraJIN/ActionRecorder#10]
I am confused about the Add-on Preferences, there are similar buttons.. I am not sure which one does what..
It would be nice to have some extra informations (a line) above these buttons to explain what they are for.

![120ii](https://user-images.githubusercontent.com/1732773/101595971-91737b00-39f4-11eb-826b-1f3b15f306f8.jpg)

**Comment by InamuraJIN** [comment]
I fixed this
It will be released soon
