### ISSUE TITLE
The + button should create an empty macro (instead of duplicating the previous one)

### ISSUE THREAD

**Issue by xan2622** [InamuraJIN/ActionRecorder#11]
After a Macro is created, if you click on the + button, it duplicates the macro (in fact it doesn't duplicate it: [it adds the last operator that has been performed in the viewport](https://github.com/InamuraJIN/ActionRecorder/issues/12)).
 
I think it should just add an "Empty" macro, ready to be edited.

![230714](https://user-images.githubusercontent.com/1732773/101596348-30987280-39f5-11eb-9d6e-6704d9c7c132.jpg)

**Comment by xan2622** [comment]
Or maybe, keep the + button (to add an empty macro) but add another button to duplicate the selected macro: 

![addons_development_icon-viewer_ui](https://user-images.githubusercontent.com/1732773/101600321-70625880-39fb-11eb-93c3-24f8bbacf8ad.jpg)

**Comment by xan2622** [comment]
Here is a mock-up image: 

![200608](https://user-images.githubusercontent.com/1732773/101993056-b9decc00-3cb7-11eb-9143-10a4003b4d39.png)

**Comment by InamuraJIN** [comment]
Please refer to this link
https://github.com/InamuraJIN/ActionRecorder/issues/12#issuecomment-747715165

You can use "Loop" and "LoopEnd" to do something similar
![image](https://user-images.githubusercontent.com/60126349/102547776-0afa2000-40fd-11eb-94bb-8bc8ffa68f5e.png)
![image](https://user-images.githubusercontent.com/60126349/102547738-fcac0400-40fc-11eb-9304-50971652dc3b.png)
And I've added this button
![image](https://user-images.githubusercontent.com/60126349/102547860-26fdc180-40fd-11eb-9748-256071fac9b8.png)

**Comment by xan2622** [comment]
OK, I understand. 
If I want many similar macros (Move, Move, Move, Move ...), I will use _Loop_ and _EndLoop_.
Thanks. 👍
