### ISSUE TITLE
Give more information in tooltips

### ISSUE THREAD

**Issue by xan2622** [InamuraJIN/ActionRecorder#13]
Some tooltips are not very clear. They don't give enough information.

![2118312](https://user-images.githubusercontent.com/1732773/101597550-22e3ec80-39f7-11eb-9b8e-733e81c7b813.jpg)

In this example, why is there "Value"?  What does it mean?
I think the tooltip should contain a line like "Click this button to select this Macro". Then, you will be able to copy it to Local if you want to".

**Comment by InamuraJIN** [comment]
I fixed this
It will be released soon

**Comment by xan2622** [comment]
I think the tooltip should contain "Move Action button up." : ("Action" is missing)

![Capture d’écran 2020-12-23 222331](https://user-images.githubusercontent.com/1732773/103038034-a3fdc080-456d-11eb-9697-7ced4bde00d1.jpg)

---

I suggest: "Move the selected Action button into another category."

![Capture d’écran 2020-12-23 222731aaaa](https://user-images.githubusercontent.com/1732773/103038183-1cfd1800-456e-11eb-8c9a-270d66a0d08d.jpg)
