### ISSUE TITLE
Recording a Bevel doesn't work well

### ISSUE THREAD

**Issue by xan2622** [InamuraJIN/ActionRecorder#14]
Add-on version: 3.5.15
Blender version: 2.91 (stable)

I am using Blender 2.91 (official stable version) and after copying the Bevel macro to Local, I tried to play it on an edge. But nothing happened.

When I manually add a bevel on an edge by myself (ctrl+b) here is what I see in the Info Editor (and it works): 
bpy.ops.mesh.bevel(offset=0.2, offset_pct=0, affect='EDGES')

But when I edit the Bevel macro in Action Recorder, it seems different (and it doesn't work):
bpy.ops.mesh.bevel(offset=0.15, offset_pct=0, vertex_only=False)

Maybe this "Bevel" macro of Action Recorder doesn't work because the operator has changed in Blender 2.91 API ?

![08_214049](https://user-images.githubusercontent.com/1732773/101597737-69d1e200-39f7-11eb-967a-e044d21eff9c.jpg)

**Comment by InamuraJIN** [comment]
How did it perform?
I couldn't reproduce it.
![ghjghg](https://i.imgur.com/R6kLfLI.mp4)
If you use the supplied action, you may have to create it yourself
The Python API changes so often that I can't keep changing it all the time.
The included actions should be used as templates only

**Comment by xan2622** [comment]
When I record a macro by myself (with the "Record" and "Stop" buttons), the "Bevel" macro that is added to the Macro Editor is the same as yours, it works fine.

` Bevel 2.91 API: `
 `bpy.ops.mesh.bevel(offset=0.360303, offset_pct=0, affect='EDGES')`

But indeed, if I use the "Bevel" macro that you provided in the Example category (Global), the following operator doesn't work: 

` Action Recorder's default Bevel macro (Global, in the "Example" Category): `
` bpy.ops.mesh.bevel(offset=0.15, offset_pct=0, vertex_only=False)`

👉  This is what this bug report (this Github issue) is about: 
> The Python API changes so often that I can't keep changing it all the time.

This might be a problem for your add-on to be accepted inside Blender (https://developer.blender.org/T79717)

When a developer asks for integrating his/her add-on in Blender (in Preferences > Addons > Community), the developer agrees to always make it compatible with the latest version of Blender (2.83 LTS and 2.91 at the moment). The developer has to follow API changes and update the add-on to make sure it works. 

That means that your examples of macros (in Global) must also be compatible with Blender 2.83 LTS and 2.91. 
Sorry to tell you that (it requires you to update the operators of your macros, in the Global examples.

**Comment by InamuraJIN** [comment]
OK thank you
I'm working on a couple of solutions now.
Worst case, I'll attach a "note" to the template action

**Comment by xan2622** [comment]
After testing with the add-on version 3.5.6, all examples of _Global Actions_ seem to work fine with Blender 2.91. 👍
