### ISSUE TITLE
Categories names overlap after clicking on Down Arrow

### ISSUE THREAD

**Issue by xan2622** [InamuraJIN/ActionRecorder#15]
I clicked on the Bottom Arrow button (to move down the "UV mode" category) but the label overlapped the other category:

![08_215523](https://user-images.githubusercontent.com/1732773/101597968-ba493f80-39f7-11eb-95ee-046d6dcdfe83.jpg)

**Comment by InamuraJIN** [comment]
I fixed this
It will be released soon

**Comment by xan2622** [comment]
I confirm this is fixed in 3.5.6 👍
