### ISSUE TITLE
ActRec duplicates recorded macros when the Operator Context Menu is used

### ISSUE THREAD

**Issue by xan2622** [InamuraJIN/ActionRecorder#16]
Animated GIF (sorry for the slow speed)

![WlvUh5EdpS](https://user-images.githubusercontent.com/1732773/101599732-8cb1c580-39fa-11eb-8c37-57b26a9055cf.gif)

After recording a "Bevel" macro (with 3 segments, with the Operator Context Menu), here is what happens: 
- it records 2 Bevels
-  then when I play the macro, it doesn't create the Bevel with the same settings that I typed in the Contextual Menu (the popup that appears at the bottom left corner of the viewport):

**Comment by InamuraJIN** [comment]
Please refer to this link
https://github.com/InamuraJIN/ActionRecorder/issues/12#issuecomment-747715165

**Comment by xan2622** [comment]
From the [#12 (comment)](https://github.com/InamuraJIN/ActionRecorder/issues/12#issuecomment-747715165): 

```
Sorry.
"Record" isn't very accurate.
It has quite a few quirks.
https://youtu.be/FqXxuMHuktc?t=8
pls Look at this video.
E.g.
As Xan said, when you use the Operator, multiple Macro get recorded.
Unintended macros, such as vertex selection, may also be recorded.

It is not possible for me to define which Macro to record automatically and which Macro to ignore.
If the API changes, it could be very version dependent.
The "+Button" is necessary for manual recording

However, the problem of multiple Macros being registered in AutoRecord will be resolved eventually.
Right now, I don't know of a workaround yet
```

OK, I understand.
I hope that maybe one day, you find a way to make the "Record" filter unwanted macros/operators.
