### ISSUE TITLE
Extrude Normal and Value Randomize

### ISSUE THREAD

**Issue by enzyme69** [InamuraJIN/ActionRecorder#2]
Hi Jin-san, thanks for this awesome addon. It reminds me of CommandRecorder addon but a bit cleaner.

I wonder what's your tips if I want to make procedure macro, but also want a bit of adjustment / variation, random values?

Let say I like just random extrusions, but I need to change value and I also need to extrude normal, what do you think?

**Comment by enzyme69** [comment]
My problem with extrude but not normal:

<img width="504" alt="Screen Shot 2020-08-24 at 1 18 55 pm" src="https://user-images.githubusercontent.com/3952687/91000367-5fd4d080-e60c-11ea-9a93-34bd3f71ce4e.png">

**Comment by InamuraJIN** [comment]
> Hi Jin-san, thanks for this awesome addon. It reminds me of CommandRecorder addon but a bit cleaner.
> 
> I wonder what's your tips if I want to make procedure macro, but also want a bit of adjustment / variation, random values?
> 
> Let say I like just random extrusions, but I need to change value and I also need to extrude normal, what do you think?

Random functions are not available.
Stay tuned for the next update!

**Comment by InamuraJIN** [comment]
> My problem with extrude but want normal direction:
Blender specifications have changed.
Alt+E>Extrude faces Along Normals
![image](https://user-images.githubusercontent.com/60126349/91078416-8da62d80-e67d-11ea-829a-3ee3a52c7b77.png)

**Comment by enzyme69** [comment]
Thanks Jin, issue resolved!
