### ISSUE TITLE
Recording of Bezier Control editing

### ISSUE THREAD

**Issue by fredleefarr** [InamuraJIN/ActionRecorder#22]
Blender version: 2.92.0
Add-on version: 3.5.6

Issue: Bezier curve editing is not recorded.

To Reproduce:

1. Click "record" in ActionRecorder
2. Create a Bezier Curve
3. Press Tab to go into edit mode
4. Move one of the control points
5. Press Tab to go into object mode
6. Stop recording in ActionRecorder
7. Press Play
8. Notice that the curve edit is not recorded

This issue I think is more to do with Blender than ActionRecorder. When clicking to select one of the control points, blender does not produce a command. The recorded bpy.ops.transform.translate therefore does not know which control point has been selected. 

The command which Blender doesn't output would be something like:

bpy.data.curves['BezierCurve'].splines[0].bezier_points[0].select_control_point = True

**Comment by InamuraJIN** [comment]
Thanks for downloading it!

You can't define a selection with mouse in ActRec
Examples of macros available in ActRec
```
Ctrl+NumPad+
Ctrl+NumPad-
Ctrl+L
Ctrl+I
Shift+Ctrl+M etc...
```
(Only if you can select with keyboard shortcut keys only)
