### ISSUE TITLE
Not working in latest blender

### ISSUE THREAD

**Issue by Patrikgrinsvall** [InamuraJIN/ActionRecorder#24]
It just doesnt show up in menu. But the console says its installed.

**Comment by InamuraJIN** [comment]
Thanks for installing it.
What version of Blender do you have?

**Comment by Patrikgrinsvall** [comment]
I tried with e-cycles 2.91, k-cycles 2.91(or maybe .93), blender original 3.0 and 2.93.

basicly i didnt get it to work after 2.89 in any config.

**Comment by versluis** [comment]
@Patrikgrinsvall I had a similar problem and thought it wasn't working, but does actually work great in Blender 3.0 and 2.9 alike. I hadn't installed it properly: you don't download the release, you have to download the whole ZIP from the Master branch. This creates the ZIP one level above it, which includes the .py files Blender needs to recognise it as an add-on. Hope this works for you as it did for me.

**Comment by InamuraJIN** [comment]
ActRec is now compatible with exactly 3.0!
I'm looking for people to be testers.
You can also report bugs on Discord!
Check out our latest news!

**Comment by RivinHD** [comment]
Fixed with [Release 4.0.2](https://github.com/InamuraJIN/ActionRecorder/releases/tag/4.0.2)
