### ISSUE TITLE
Can't assign shortcut for any button

### ISSUE THREAD

**Issue by fleewortep** [InamuraJIN/ActionRecorder#26]
There is no option for assign shortcut when right click

![Screen Shot 2022-02-03 at 15 17 59](https://user-images.githubusercontent.com/13103600/152341368-919e74b2-ed66-4ab2-ae49-5a434600536e.png)

**Comment by InamuraJIN** [comment]
OK
I'm trying to figure out what caused it

**Comment by fleewortep** [comment]
is there a way it can be fixed soon?

**Comment by gromafon2** [comment]
Hi! I have the same problem in Blender 2.93 and 3.0. There is no way to assign a hotkey. It will be awesome if you can fix it. 
P.S. Thanks for the addon, it's incredibly useful!

**Comment by fleewortep** [comment]
the oly key you can assign shortcuts to is PLA
![Screen Shot 2022-02-19 at 22 47 45](https://user-images.githubusercontent.com/13103600/154834930-4cf655c4-6f11-4603-a146-c7e63aff9876.png)
Y

**Comment by gromafon2** [comment]
> the only key you can assign shortcuts to is PLA ![Screen Shot 2022-02-19 at 22 47 45](https://user-images.githubusercontent.com/13103600/154834930-4cf655c4-6f11-4603-a146-c7e63aff9876.png) Y

Yes, I know. I'm looking for a way to assign a hotkey directly to the macros themselves. I usually call macros from the quick favorites menu. But there are already a bunch of buttons and it takes time to find the right one. I want macros to be hotkeys to do less actions. And working in a blender was like maaagic)))

**Comment by fleewortep** [comment]
>  I want macros to be hotkeys to do less actions. And working in a blender was like maaagic)))

totally agree

**Comment by RivinHD** [comment]
Good news, it now works in [Version 4.0.2](https://github.com/InamuraJIN/ActionRecorder/releases/tag/4.0.2)
