### ISSUE TITLE
Play Action on all selected objects

### ISSUE THREAD

**Issue by Draise14** [InamuraJIN/ActionRecorder#27]
At the moment it's great for a 1 object at a time workflows (active). It would be nice to be able to run the script on all selected objects. 

```
import bpy

for obj in bpy.context.selected_objects:
    bpy.context.view_layer.objects.active = obj

    # Put Operator Chain here
    bpy.ops.ar.record_play()
```
I use this script to do this, but if the button had this built in it would be great. Run on all selected.

**Comment by InamuraJIN** [comment]
Thank you!
I'll give it a try
If you don't mind, please fork the Dev version and push it!
https://github.com/InamuraJIN/ActionRecorder/tree/Dev
