### ISSUE TITLE
CTRL+Z erases local script list

### ISSUE THREAD

**Issue by Draise14** [InamuraJIN/ActionRecorder#28]
When pressing the `CTRL+Z` button, it erases the list.

**Comment by intracube-paul** [comment]
Hi, 

I'm seeing the same issue with current ActionRecorder master, running Blender 2.90 and 3.2.2.

Steps to reproduce:
- Add a new local action and give it a custom name
- Go to edit mode, move some vertices and then undo (ctrl+z)
- The local action name will reset to default, eg 'Untitled.001' (see screenshot)
![action_recorder_undo_bug_01](https://user-images.githubusercontent.com/12416914/188290099-e7d64b97-444d-44cb-b7e7-00abeaffd4dd.png)

Notes:
- The most recently created local action (lowest in list) is affected - not whichever is highlighted/selected.
- A workaround is to create a spare (blank) local action. Any undo operation will then just reset that.
- Interestingly, if this spare local action is removed, the previous action in the list is no longer affected by the bug.

Other than this issue, a great addon!

**Comment by RivinHD** [comment]
Fixed with [Release 4.0.2](https://github.com/InamuraJIN/ActionRecorder/releases/tag/4.0.2)
