### ISSUE TITLE
Can't Record vertex Rip action

### ISSUE THREAD

**Issue by JustinMailx** [InamuraJIN/ActionRecorder#29]
Hi I want to make record the Rip vertex action.
while it does record the action, it does not actualy rip the vertexes when playing the action over.

And Seperate selection ( Shortkey "p") wil not record at all.

Can this be fixed?
Using blender 3.0.1

**Comment by InamuraJIN** [comment]
New version released

**Comment by RivinHD** [comment]
Fixed with https://github.com/RivinHD/ActionRecorder/commit/655eac9c945644d62d80355cc2a06acf4126384b
