### ISSUE TITLE
Doesn't work in 3.1x

### ISSUE THREAD

**Issue by wonderland78** [InamuraJIN/ActionRecorder#30]
Wish this would update, it was SO useful.

**Comment by intracube-paul** [comment]
Interestingly, the current release of the addon appears to work for me on Blender 3.2.2 (Linux, x86_64).

The only issue is a bug which resets the action name after an undo (ctrl+z). See https://github.com/InamuraJIN/ActionRecorder/issues/28

This bug affects the addon running on Blender 2.90 and 3.2.2.

**Comment by RivinHD** [comment]
Fixed with [Release 4.0.2](https://github.com/InamuraJIN/ActionRecorder/releases/tag/4.0.2)
