### ISSUE TITLE
Missing Global Actions, if the Internet connection is dissable.

### ISSUE THREAD

**Issue by vtALEXANDER** [InamuraJIN/ActionRecorder#4]
Good day. 

Thank you for your hard work. 

Windows 10; Blender 2.83.4; Action Recorder 3.4.1; 

The macro buttons of Action Recorder add-on disappear in the Global Actions column (the entire column becomes empty), if the computer is disconnected from the Internet. 

If the Internet connection is reopened, the macro buttons reappear in Global Actions. 

What could be the problem and how it can be fixed? 
Is the add-on connecting to something in the Internet to work?

**Comment by InamuraJIN** [comment]
Thanks for the report!
I'll check and fix it
> Is the add-on connecting to something in the Internet to work?
Yes,
checking for updates to the add-ons.

**Comment by vtALEXANDER** [comment]
Thank you!

We will wait for your decision, because there is a need to work offline. 

Great add-on. Thank you!

**Comment by InamuraJIN** [comment]
thank you!
does a error appear if no internet connection is available?

**Comment by vtALEXANDER** [comment]
Thank you for reply.

If the Internet connection is available – all macros buttons in Global Action are visible, available and workable.

If the Internet connection is not available – all macros buttons in Global Action are not visible and not available. If the Internet connection is not available, the list in Global Action is empty.

Thank you!

**Comment by InamuraJIN** [comment]
OK
Please check the following actions
1.No internet connection
2. Start a new Blender Window
3. Error message is displayed in [Info] or [SystemConsole] of the image.
https://i.imgur.com/O6cOmtn.png

**Comment by vtALEXANDER** [comment]
Hello.

Here is a screenshot with toogle screen console.

https://imgur.com/IfoR4c6

**Comment by InamuraJIN** [comment]
ok thank you!
we will fix it and also make the Update!

**Comment by vtALEXANDER** [comment]
Thank you! 
It's awesome!
We will wait for it :)
