### ISSUE TITLE
install on blender V 3.4.1

### ISSUE THREAD

**Issue by eldany1972** [InamuraJIN/ActionRecorder#42]
Hi There!

I am trying to install the add-on in V3.4.1 and the install don't give any error but the add-on is not listed to enable it :(
Any clue?

zip installed is ActionRecorder-master.zip

Thanks!
Dany

**Comment by RivinHD** [comment]
Hi, 

Don't download the add-on from the code button. Always download it from releases.
You can get the latest Version [**here**](github.com/InamuraJIN/ActionRecorder/releases/latest) and then download ActionRecorder.zip

![Screenshot 2023-01-12 144043](https://user-images.githubusercontent.com/58261670/212082624-34029ab0-7d96-456c-8bc4-6f0e1d0c44c9.png)
