### ISSUE TITLE
Wrong Documentation link

### ISSUE THREAD

**Issue by xan2622** [InamuraJIN/ActionRecorder#5]
Add-on version: 3.5.15
Blender version: 2.91 (stable)

![3531](https://user-images.githubusercontent.com/1732773/101593950-296f6580-39f1-11eb-9a4a-8cb7a57d860c.jpg)

When you click on the **Documentation** button (in the Add-on Preferences), it redirects to the wrong Github page.

It leads to https://github.com/InamuraJIN/CommandRecorder/blob/master/README.md
but I think it should go to : https://inamurajin.wixsite.com/website/post/tutorial_readme_en 

Or better: copy this documentation (from your website) to the [Github Wiki](https://github.com/InamuraJIN/ActionRecorder/wiki).

**Comment by InamuraJIN** [comment]
I fixed this.
It will be released soon
