### ISSUE TITLE
Wrong operator values adding macros if operator box is changed before

### ISSUE THREAD

**Issue by GustJc** [InamuraJIN/ActionRecorder#54]
**Describe the bug**
Added or Recorded macros gets added with wrong operator parameters.

This happens because blender saves operator parameters changed by the user.

Notice on the video. 
The first time, when changing the operator 'Merge', it is properly executed as:
`bpy.ops.mesh.bridge_edge_loops(use_merge=True)`
But on the next execution. It gets called as:
`bpy.ops.mesh.bridge_edge_loops()`
Even though it is executed with use_merge=True
This is a blender problem. It doesn't pass the operator values that has been changed by the user and uses a 'cached' value in the blender session somehow.

Not sure how to solve this. But this is very bad and can lead to a lot of confusion and problems if the user doesn't know about it.

![operator_problme](https://github.com/InamuraJIN/ActionRecorder/assets/3084189/d01fab70-93d9-45b5-8580-5627fa2430ea)

**To Reproduce**
1. Execute a command and change a value on the operator box
2. Undo the command.
3. Execute it again. The changed value is already there now.
4. Add the macro with the '+' button
5. Execute the macro

**Expected behavior**
Should be able to understand changed values on the operator box.

**Version Information:**
 - Add-on Version 4.0.8
 - Blender Version 3.6
 - OS: Windows 10

**Comment by RivinHD** [comment]
Thanks for reporting this bug.

I think it is fixable.
Blender provieds some more past state data for operators other than the reports.

**Comment by RivinHD** [comment]
This is already fixed in the current development version

**Comment by RivinHD** [comment]
Fixed with [Version 4.0.1](https://github.com/InamuraJIN/ActionRecorder/releases/tag/v4.1.0)
