### ISSUE TITLE
Default Global actions(Storage.json) have deprecated and old code, which doesn't work

### ISSUE THREAD

**Issue by GustJc** [InamuraJIN/ActionRecorder#55]
**Describe the bug**
Global actions that ships with the addon have deprecated code. (https://github.com/InamuraJIN/ActionRecorder/blob/master/ActRec/Storage.json)
The global actions from External->Scatter and BackUP don't work.
Might be others, I haven't checked all.

Looking around, it seems they originally depended on https://github.com/RivinHD/ScriptToButton/tree/master
And on local configuration files of it. Calling commands like 
`bpy.ops.stb.scriptbutton(btn_name=\"PlayAnim3\")`
Also, the other addon seems to use script_button now, so this should be some pretty old code that was left over.

It would also be nice if the default global actions included some of the actions shown in the "Product Movie" trailer video.
https://www.youtube.com/watch?v=OA0vjP7D4Ec&t=58s
Just so we have some more examples of its utility to explore. The video shows the "slow/before version" so its nice to see what macros that translates to. 
I can't quite figure our how to translate that hair mesh alignment one into macros, for example.

**To Reproduce**
1. Rename the name to "Passive" (scatter seems to search for that object to work on)
2. Execute the global action Scatter

**Expected behavior**
Scattered objects.
But gets error while trying to call `bpy.ops.stb.scriptbutton`

**Version Information:**
- Add-on Version 4.0.8
- Blender Version 3.6
- OS: Windows 10

----------------
PS:
Trying to run an action with the execution mode ´Individual´ does not work.
I was going to make a PR to fix this but it seems you(@RivinHD) already fixed this in your local fork quite a while back.
It's just that its not merged here yet.
Not sure if I should post an issue here to keep track or not. Or just wait for the next minor release.
So adding this section here, so you can decide.

**Comment by RivinHD** [comment]
I wanted to make this release quite a while ago, but I wanted to finish a new documentation that is hosted by [github pages](https://pages.github.com).
And also finish and review the current opened bug reports.

**Comment by RivinHD** [comment]
Fixed with [Version 4.0.1](https://github.com/InamuraJIN/ActionRecorder/releases/tag/v4.1.0)
