### ISSUE TITLE
Blender 4.1 Bug - Font DejaVu not found

### ISSUE THREAD

**Issue by Draise14** [InamuraJIN/ActionRecorder#59]
**Describe the bug**
When clicking on the Macro Editor to edit an action, I get an error looking for the DejaVu font, which now is no-longer used in Blender 4.0+. 

**To Reproduce**
1. Go to 'Macro Editor panel'
2. Click on a new action to edit it
3. See error

**Expected behavior**
No error

**Screenshots**
![image](https://github.com/InamuraJIN/ActionRecorder/assets/35357409/ff48306c-bc95-464b-85e1-b467adf4d32c)

**Version Information:**
 - Add-on Version [e.g. 4.0.8]
 - Blender Version [e.g. 4.1.0 + 4.0.2]
 - OS: Windows

**Comment by Draise14** [comment]
![image](https://github.com/InamuraJIN/ActionRecorder/assets/35357409/67ca3e52-8735-499e-9e76-58af1daddcad)

Fix is simple, update the font check for versions. 

Very sophisticated addon!

**Comment by Iziaky01** [comment]
The solution shown above is correct! Thank you :) 

To fix this issue, follow these steps:
- close Blender 4.0
- go to:
C:\Users\*******\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ActionRecorder\actrec\functions
- search for `shader.py` file
- open it (I used _Sublime_ software)
- search for `get_font_path`
- check some lines below for DejaVuSans.woff2 and change it to Inter.woff2
- save file
- open Blender 4.0 and a Project
- open your ActionRecorder tab, and click on a new Action. Now it should highlight without any working!

**Comment by Skytale23** [comment]
M1
Mac OS 14.3.1
Blender Version 4.0.2
Add-on Version 4.0.8

Oddly enough - and don't ask me why - I kept on gettin the above error but with inter.woff2 as the missing font when I edited the shared.py file as mentioned above with XCode , but.... by deleting the '2' from 'Inter.woff2' I actually got this to work on my M1 Mac.

**Comment by RivinHD** [comment]
I created a development release as a [temporary solution](https://github.com/InamuraJIN/ActionRecorder/releases/tag/devTo4.1.0)
The font issue is fixed in this version, other bugs have to be checked before the release.

**Comment by RivinHD** [comment]
Fixed with [Version 4.0.1](https://github.com/InamuraJIN/ActionRecorder/releases/tag/v4.1.0)
