### ISSUE TITLE
Select the newly created macro

### ISSUE THREAD

**Issue by xan2622** [InamuraJIN/ActionRecorder#6]
Would it be possible to select the new Macro, when it is created?

In the following screenshot, you can see that the first macro is still being selected. It would be less confusing if the selected line would be the one that has just been created with the + button.

![235](https://user-images.githubusercontent.com/1732773/101594264-ab5f8e80-39f1-11eb-8976-56b51da6f948.jpg)

**Comment by InamuraJIN** [comment]
I fixed this
It will be released soon

**Comment by xan2622** [comment]
I confirm this is fixed in 3.5.6 👍
