### ISSUE TITLE
Paypall won't let me donate to you

### ISSUE THREAD

**Issue by oquigley** [InamuraJIN/ActionRecorder#60]
Hello,

When I tried to send a paypal donation to thank you for Action Recorder, paypal said that your account could not receive any more money until you "provided paypal with more information" whatever that means.
Action Recorder is very useful, and I'd like to donate to thank you for your work but it doesn't seem like there's any way to do that.

Thanks-
Ocean

**Comment by InamuraJIN** [comment]
Thanks for reporting it!
I fixed it
