### ISSUE TITLE
Does not install in 4.0.2

### ISSUE THREAD

**Issue by davek1979** [InamuraJIN/ActionRecorder#61]
Following the install procedure, install succeeds but add-on does not appear in the list when searched for.

**Comment by peterwc** [comment]
I can confirm this as well. I just found your code today, but it is saying the installation is working. However, the side panel is not appearing.

**Comment by repusman** [comment]
Yup exact same issue for me.  Install seems normal but no plugin is there.

**Comment by Skytale23** [comment]
I had to unzip the code as downloaded from here and then reZip the ActRec file within the decompressed file (without the testing file or the various .txt or .json); then followed this fix - https://github.com/InamuraJIN/ActionRecorder/issues/59.

Not sure whether I have all of the functionality of the original but it seems to record multiple macros, saves and moves from Local to Global and works quite well, within certain limitations.

**Comment by RivinHD** [comment]
I created a development release as a [temporary solution](https://github.com/InamuraJIN/ActionRecorder/releases/tag/devTo4.1.0)
The font issue is fixed in this version, other bugs have to be checked before the release.

**Comment by peterwc** [comment]
Dev branch mentioned allows installation! and I can record!

**Comment by RivinHD** [comment]
Fixed with [Version 4.0.1](https://github.com/InamuraJIN/ActionRecorder/releases/tag/v4.1.0)
