### ISSUE TITLE
Error when deleting Actions 4.0.8

### ISSUE THREAD

**Issue by Iziaky01** [InamuraJIN/ActionRecorder#64]
**Describe the bug**
I get this error when I'm trying to delete any action I created, and moved from Local to Global. Updated lastly to version 4.0.8 with Blender 4.0.2
(check video)

**Expected behavior**
Delete Action like it does in previous version.

**Screenshots**

https://github.com/InamuraJIN/ActionRecorder/assets/158458961/ef046b5c-7f63-4c80-83d0-fd741f0c2d35
![OjjlprhXuP](https://github.com/InamuraJIN/ActionRecorder/assets/158458961/42367408-4f61-4169-bc15-b3f424f6c45d)

**Version Information:**
 - Add-on Version [4.0.8]
 - Blender Version [4.0.2]
 - OS: [Windows]

**Comment by RivinHD** [comment]
Thanks for reporting

**Comment by RivinHD** [comment]
Fixed with [Version 4.0.1](https://github.com/InamuraJIN/ActionRecorder/releases/tag/v4.1.0)
