### ISSUE TITLE
The steps to copy a Local macro to Global are not clear

### ISSUE THREAD

**Issue by xan2622** [InamuraJIN/ActionRecorder#7]
I think the process to copy Local macros to Global is not very clear.
When I clicked on the "Local to Global" button, a message appeared: "Record to button".

At first I thought "What does this mean? What do have I to do?" But after watching the video tutorial, I have been able to understand that I first had to create a category in the "Advanced" drop-down menu. 

It's cool that there are [videos](https://www.youtube.com/watch?v=PX1O5SoYe88&list=PLz0bMWD4uyi661zRtioCFGv9Vjv3d_Rn6) (they help) but I think that adding Macros to Global could be better explained without needing to read docs. 

Suggestion: When there's no category, instead of showing the "Record to button" message, maybe there could be a message like "Add a Category first. To do that, go to the Advanced drop-down menu".

![224823](https://user-images.githubusercontent.com/1732773/101594467-009ba000-39f2-11eb-8840-e8954d390449.jpg)

**Comment by InamuraJIN** [comment]
I fixed this
It will be released soon
