### ISSUE TITLE
Difficult to know where to click to add or change the icon

### ISSUE THREAD

**Issue by xan2622** [InamuraJIN/ActionRecorder#8]
Without watching the video tutorial or reading the documentation, the user can't know where he/she has to click to add an icon.
By default the line doesn't show anything.

![211052](https://user-images.githubusercontent.com/1732773/101595509-bb786d80-39f3-11eb-9836-24a8be2c1f3c.jpg)

I think that there should be a solid color :blue_square: or a square :white_square_button: to indicate the user where to click to change the icon.

![211053](https://user-images.githubusercontent.com/1732773/101595516-bddac780-39f3-11eb-8a31-5f2e14f4f94b.jpg)

![211830](https://user-images.githubusercontent.com/1732773/101595529-c3d0a880-39f3-11eb-93fa-7ea7a76ba095.jpg)

**Comment by InamuraJIN** [comment]
I fixed this
It will be released soon
