### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by xan2622** [InamuraJIN/ActionRecorder#9]
I have noticed a small typo in the Add-on Preferences: 

"Strage" instead of "Storage"
![11523](https://user-images.githubusercontent.com/1732773/101595844-596c3800-39f4-11eb-997e-65fea580a30e.jpg)

"Delet" instead of "Delete"
![211831](https://user-images.githubusercontent.com/1732773/101595879-64bf6380-39f4-11eb-93a5-1bea695655a3.jpg)

**Comment by InamuraJIN** [comment]
I fixed this
It will be released soon
